---
title: "**MODELO PARA LA PREDICCIÓN DE LA DEMANDA MENSUAL DE HORAS DE MAQUINARIA AGRÍCOLA EN LA MUNICIPALIDAD DISTRITAL DE CARACOTO 2020**"
author: "Bach. Betho Mamani Condori"
date: "30/10/2020"
output: 
  revealjs::revealjs_presentation:
    theme: beige
    highlight: pygments
    center: true
    self_contained: false
    reveal_plugins: ["notes", "search"]
    reveal_options:
      slideNumber: true
      previewLinks: true
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true  
---

# DESCRIPCIÓN DEL PROBLEMA

La Municipalidad Distrital de Caracoto, cuenta con una gran cantidad pobladores de área rural, por lo cual tiene una **gran cantidad de agricultores**, que necesitan el apoyo de la municipalidad brindándole el **servicio de maquinaria agricola** a tiempo y con un costo accesible para el arado y distintas operaciones que permite la maquinaria agraria, de esta manera **aportar a la producción** de alimentos andinos y economía de los agricultores.

# FORMULACIÓN DEL PROBLEMA

**¿Cuál es el modelo que mejor se ajusta para predecir la demanda mensual en horas de maquinarias para los agricultores del Distrito de Caracoto?**

# OBJETIVOS

## Objetivo General
Determinar el **mejor modelo** que se ajuste para predecir la demanda mensual en horas de
maquinarias, a través de la **metodología Box-Jenkins** para los agricultores del Distrito de Caracoto – 2020. 

## OObjetivos Específicos

•	**Explorar la serie de tiempo** de horas de trabajo mensual de las maquinarias agrícolas de la Municipalidad Distrital de Caracoto.

•	Encontrar y validar el **modelo identificado que mejor se ajusta** para la serie de las horas de trabajo mensual de las maquinarias agrícola de la Municipalidad Distrital de Caracoto.

• Determinar el **pronóstico con el modelo alcanzado** para la serie de tiempo de la demanda mensuales de horas de maquinaria agrícola en la Municipalidad Distrital de Caracoto.

# HIPOTESIS

## Hipótesis General

El modelo usando la metodología **Box–Jenkins** proporciona un mejor ajuste para predecir la demanda mensual de horas de maquinarias agrícola en la Municipalidad Distrito de Caracoto.

# JUSTIFICACIÓN DE LA INVESTIGACIÓN

##
  * El proyecto se consideró muy necesario, ya que la Municipalidad cuenta con gran cantidad de agricultores que se dedican al sembrío, en grandes cantidades por lo cual es **necesario el arado de sus tierras**.
  
  * El modelo es necesario para **predecir la demanda de los próximos meses** y de esta manera la municipalidad distrital podrá **atender a tiempo las solicitudes de maquinarias** para el arado, se tendrá operarios a tiempo y combustible.

# ANTECEDENTES DE LA INVESTIGACIÓN

## A Nivel Internacional

<small>(Morales Zapata, 2015) En la presente investigación “diseño de un sistema de arado para la preparación del suelo en cultivos orgánicos dirigido a pequeños agricultores” presentó la labranza cero o siembra directa como una técnica conservadora de producción agrícola que ha surgido como respuesta a la degradación de los recursos, principalmente del suelo y del medio ambiente, dando como resultado ciertos beneficios que serán expuestos para demostrar la productividad y sostenibilidad de este sistema.</small>

<small>(Bernejo Mancera, 2011) En su trabajo de investigación “Métodos estadísticos en series temporales no lineales, con aplicación en energía eólica” cuyo objetivo fue desarrollar técnicas para mejorar la implementación de modelos de series temporales no lineales, con especial énfasis en la predicción de potencia eólica. Llegando a la conclusión que el modelo SETARTVCD Presupuesto es una buena alternativa para predecir la producción eólica.</small>

<small>(Villazón Bustillos, Rubio Arias, & Ortega Gutierrez, 2015) En la presente investigación “Análisis en series de tiempo para el pronóstico de sequía en la región noroeste del estado de Chihuahua” Concluye que se empleó el modelo ARIMA con estacionalidad de nueve años, se simulo la precipitación del 2000 al 2012 y se pronosticó del 2013 al 2024. Se concluye que entre el 2018 y 2019, ocurrirá una sequía de moderada a severa en la región noroeste del estado de Chihuahua.</small>

## A Nivel Nacional

<small>(Huillca Vargas, 2017) El desarrollo del presente trabajo de investigación; cuyo objetivo principal es modelar el comportamiento de los ingresos diarios en nuevos soles y la cantidad de bicicletas que ingresan a diario al taller de bicicletas SAN LUIS utilizando los modelos ARIMA. En el segundo capítulo se presenta los conceptos teóricos de Series de Tiempo, los modelos clásicos de descomposición de una serie de tiempo, los modelos AR, MA, ARMA, ARIMA, SARMA, SARIMA, así como la metodología de ajuste de estos modelos, que consiste en 4 etapas que son: identificación, estimación, validación y predicción. Utilizando los paquetes estadístico SPSS versión 22, MINITAB versión 17 y EVIEWS versión 9.</small>

<small>(Modesto Arias, 2017) “Comportamiento de la demanda de depósitos a plazo fijo en moneda nacional en las cajas municipales periodo 2004 - 2016” En su trabajo de investigación. Se empleo método econométrico tradicional y serie de tiempo con interés de contrastar los resultados. Se evaluó la capacidad de predictiva mediante criterios de información, evaluación de residuos y error de pronóstico. se concluye que la mejor alternativa es plantear un modelo ARIMA, ya que de considerar otra variable explicativa se obtiene una regresión espuria.</small>

<small>(Rugel Barreto, 2011) “Modelos de Pronostico de Estadísticas Vitales en la Provincia de Huaraz a Nivel de Centros Poblados 2011” El objetivo de la presente investigación fue encontrar los modelos de pronósticos que mejor se ajustan a los datos. Se aplicó Metodologías de Box-Jenkins, Modelos de Regresión Múltiple, Modelos de Ajuste Estacional con Census Xll y Ajuste de datos a la Función Logística.</small>

## A nivel Local

<small>(Melo Mayta, 2016) “Modelo de predicción mensual de Mortalidad General Intrahospitalaria en el Hospital Regional Manuel Núñez Butron – Puno, 2008 – 2016 - I” Usando la metodología usada fue Box – Jenkins para el modelamiento de la serie del número de mortalidad general intrahospitalaria. El resultado de la estimación del mejor modelo univariante para la predicción de la serie original de mortalidad intrahospitalaria, en el Hospital Regional Manuel Núñez Butron – Puno es un modelo SARIMA(2,1,0)(0,1,1)(12)</small>

<small>(Bedoya Luza, 2018) “Modelamiento univariado del número de defunciones infantiles producidas por infecciones respiratorias agudas, a través de la metodología box-jenkins, puno 2008-2016” El resultado obtenido de esta investigación, el mejor modelo univariante para pronosticar la serie del número de defunciones infantiles causadas por las infecciones respiratorias agudas (I.R.AS), en niños menores de 05 años de la Dirección Regional de Salud de Puno es el modelo ARIMA (0, 1,1,)x(1, 1,0)</small>

# DEFINICIÓN DE TÉRMINOS BÁSICOS

## Maquinarias Agrícolas

* (Murillo, 1987) Sostiene que, un tractor es una maquina dotada de motor para su desplazamiento, puede ser usada para tirar de equipos como arados, restras, etc. O para accionar mecanismos de máquinas estacionarias trilladoras, etc. Y de máquinas móviles como empacadores y segadoras.

## Municipio

* Es la entidad administrativa que se puede agrupar una sola localidad o varias y que puede ser un hacer referencia a una cuidad, un pueblo o una aldea.

* Un municipio es, al mismo tiempo, una división territorial y una entidad administrativo de nivel local, constituida por territorio, población y poderes públicos. En este sentido, es un ente organizativo dentro del Estado que goza autonomía gubernamental y administrativa, cuya función es gestionar los intereses de una comunidad y dar solución a sus problemas. (Coelho, 2018)

## Modelo

* Según (Kishurim, Tecnice, Tecnimat, Griduc, & Gidsaw, 2013) el modelo consiste en la especificación formal de los elementos de un sistema, las relaciones entre mismos y los parámetros que permiten contextualizar el desempeño del sistema de acuerdo con las características del entorno y las relaciones del sistema del mundo real con el mismo.

## Predicción

* Las ideas anteriores pueden servir de ayuda en el importante problema de la predicción en las series de tiempo. Sin embargo, se debe tener en cuenta que un tratamiento matemático de los datos no resuelve por si solo todos los problemas.

* Justamente con el sentido común, experiencia, habilidad y buen juicio del investigador, tales análisis matemáticos pueden, no obstante, ser de valor para la predicción a largo y corto plazo. (Murray Ralph & Larry J, 2009)

# MARCO TEÓRICO

## Metodologías de diseño de investigación

(Valadez Silvas, 2019) Dentro de las partes del diseño de información se encuentra el análisis y la reflexión de la teoría y metodóloga del deseño. Que lo que nos ayuda a organizar nuestras ideas para finalmente tomar la mejor que se adecue a lo que queremos. El diseño surge para resolver necesidades y problemas.

En el presente trabajo se revisaron las siguientes metodologías.

## Metodología de Bruno Munari

* Características (Munari, 1985):
  + Es un método lineal y presenta orden lógico
  + Todo problema es susceptible de descomponerse en pequeños problemas o subproblemas.
  + Su finalidad en conseguir un máximo resultado con mínimo esfuerzo.

## Metodología de Hans Gugelot

* Características (mclaranarvaez, 2017):
  + Presentación del problema
  + Análisis del estado actual
  + Definición del problema y las metas
  + Creaciones alternativas
  + Evaluación y selección
  + Planificación de la producción metodológica

## Metodología de Gui Bonsiepe

* Características (Mendez Lima, 2018):
  + Análisis funcional
  + Análisis morfológico
  + Sinéctica
  + Síntesis formal
  + Optimizar características de uso
  + Visualización de ideas

## Metodología de Christopher Alexander

* Características (Sarli, 2017):
  + Reducción de tiempos
  + Reducir esfuerzo de mantención
  + Aumentar la eficiencia
  + Aumentar la fiabilidad
  + Proteger la inversión

## Metodología de Hernández Sampieri Roberto

* Enfoque cuantitativo (Tesis de Investigadores, 2011):
  + Las hipótesis se generan antes de recolectar y analizar los datos
  + La recolección de los datos se fundamenta en la medición
  + La recolección de los datos se fundamenta en la medición
  + se representan mediante números (cantidades) y se deben analizar a través de métodos estadísticos
  + Lograr que otras explicaciones posibles distintas a la propuesta del estudio (hipótesis) sean desechadas.
  + Los análisis cuantitativos se interpretan de las predicciones iniciales (hipótesis) y de estudios previos (teoría).

## Series de tiempo

Una serie tiempo es una secuencia de observaciones, medidos en determinados momentos del tiempo, ordenados cronológicamente y, espaciados entre sí de manera uniforme, así los datos usualmente son dependientes entre sí. El principal objetivo de una serie de tiempo es su análisis para hacer pronóstico. (Villavicencio, 2010) 

## Clasificación de Movimientos de Series de Tiempo

* Movimiento de Tendencia
* Movimiento Cíclicos
* Movimiento Estacional
* Movimiento Irregulares

## Clasificación Descriptiva de la Series de Temporales

* Estacionarias
* No estacionarias

## Utilización de las Series de Tiempo

* Economía
* Meteorología
* Geofísica
* Química
* Demografía
* Medicina
* Marketing
* Telecomunicaciones
* Transporte

## Procesos Estocásticos

Desde un punto de vista intuitivo, un proceso estocástico se describe como una secuencia de datos que evolucionan en el tiempo. Las series temporales se definen como un caso articular de los procesos estocásticos. (Hernández, 2015)

* Proceso Estocástico Estacionario
  + Un proceso estocástico se dice que es estacionario si su media y su varianza son constantes en el tiempo y si el valor de la covarianza entre dos periodos depende solamente de la distancia o rezago entre estos dos periodos de tiempo y no del tiempo en el cual se ha calculado la covarianza. (Villavicencio, 2010)
  
## Ruido blanco (“White noise”)

Un ruido blanco es un caso simple de los procesos estocásticos, donde los valores son independientes e idénticamente distribuidos a lo largo del tiempo con media cero e igual varianza,  (Villavicencio, 2010)

* se denota por:

  $$E_t~N(0,\sigma^2)cov(E_ti,E_tj)=0 ;$$ 
  $$ \forall t_i\neq t_j$$

## Prueba de Ljung – Box

(Peña, 2005) Esta prueba permite probar en forma conjunta de que todos los coeficientes de autocorrelación son simultáneamente iguales a cero, esto es que son independientes.

* está definida como:

  + $H_0:$Las autocorrelaciones son independientes (es un ruido blanco $ρ_k=0$ ).

  + $H_0:$Las autocorrelaciones no son independientes (no es un ruido blanco $ρ_k=0$ ).

## Autocorrelación

* Función de autocorrelación (ACF)

  La autocorrelación mide la correlación entre dos variables separadas por k periodos.

* Función de autocorrelación Parcial (PACF)

  La autocorrelación parcial mide la correlación entre dos variables separadas por k periodos cuando no se considera la dependencia creada por los retardos intermedios existentes entre ambas.
  
## Proceso Lineal Estacionarios 

* Proceso autorregresivos AR(p)
  
  (Bruce L, Richard T, & Anne B, 2007) Los modelos autorregresivos se basan en la idea de que el valor actual de la serie, puede explicarse en función de valores pasados $X_(t-1),X_(t-2),…,X_(t+p)$, donde determina el número de rezagos necesarios para pronosticar un valor actual.

* Modelo de medias móviles MA(q)
  
  Modelo “determinados por una fuente externa”. Estos modelos suponen linealidad, el valor actual de la serie, $X_t$, está influenciado por los valores de la fuente externa.
  
##

* Proceso Autorregresivo de Medias Móviles ARMA(p,q)

  Es muy probable que una serie de tiempo, $X_t$, tenga características de $AR$ y de $MA$ a la vez y, por consiguiente, sea ARMA. Así, $X_t$  sigue un proceso $ARMA (p,q)$, en este proceso habrá términos autorregresivos y términos de media móvil.
  
  $X_t=c+\underbrace{(φ_1 X_(t-1)+φ_2 X_(t-2)+⋯+φ_p X_(t+p)}_{AR(p)}$
    $+ \underbrace{(θ_1 ε_(t-1)+θ_2 ε_(t-2)+⋯+θ_p ε_(t-p)}_{MA(q)}+ε_t$
  

## Procesos Lineales no Estacionarios

Proceso Autorregresivo integrado y de Medias Móvil ARIMA (p, d, q)

  + <small>Los modelos de series de tiempo analizados hasta ahora se basan en el supuesto de estacionariedad, esto es, la media y la varianza para una serie de tiempo son constantes en el tiempo y la covarianza es invariante en el tiempo.</small>
 
  + <small>Pero se sabe que muchas series de tiempo y en especial las series económicas no son estacionarias, porque pueden ir cambiando de nivel en el tiempo o sencillamente la varianza no es constante en el tiempo, a este tipo de proceso se les considera procesos integrados.</small>
  
  + <small>Por consiguiente, se debe diferencias una serie de tiempo veces para hacerla estacionaria y luego aplicarla a esta serie diferenciada un modelo ARMA , se dice que la serie original es ARIMA, es decir, una serie de tiempo autorregresiva integrada de media móvil(Wilfredo Toledo, 2013).</small>

## Transformación de la Seria de Tiempo

  * El trabajo de exploración consiste en construir la gráfica de la serie de tiempo para visualizar el patrón de comportamiento y adecuarla para el uso de la metodología Box – Jenkins mediante los patrones Raíz unitaria, tendencia estocástica, tendencia deterministas y estacionariedad.  (Wilfredo Toledo, 2013)
  
  * Cuando la serie no lo es, es preciso transformarla. Este proceso es muy sencillo. Para eliminar la tendencia se toman una o varias diferencias en la serie. Una serie se diferencia restando a cada observación la observación anterior: (Wilfredo Toledo, 2013)
# tab02
### tabsss04

## Prueba de Dickey – Fuller Ampliado (ADF)

  (Robert H. & David S., September 2010) El test de Dickey – Fuller Ampliado (DFA) contrasta la presencia de una raíz unitaria en una serie que sigue un proceso $AR(p)$, deberá aplicarse el procedimiento expuesto para el caso simple $AR(1)$, pero suponiendo ahora el modelo:

  $H_0: p>0.5$ raíz unitaria (proceso no estacionario de los residuales)

  $H_1: p<0.5$ no es de raíz unitaria (proceso estacionario de los residuales)

# MATERIALES Y METODOS

## TIPO Y DISEÑO DE INVESTIGACION
  * El presente trabajo de investigación es de enfoque cuantitativo con diseño descriptivo simple según (Hernández Sampieri, Fernández Collado, & baptista Lucio, 1999).
  
  * Se realizó con datos cuantitativos por que los datos mostrados con una variable discreta, el cual se estudiaran las horas acumuladas de trabajo en meses obtenidas por la Municipalidad Distrital de Caracoto, para determinar el comportamiento con el fin de responder al planteamiento del problema, y analizar con seguridad la hipótesis formulada.
  * El alcance del presente trabajo es describir la tendencia de los datos mensuales de los 10 últimos años.

## POBLACION Y MUESTRA DE INVESTIGACION

* Población:

  La población para el presente estudio fue constituida por horas totales de trabajo acumuladas durante el mes de los últimos 10 años, que fueron registrados por la Municipalidad Distrital de Caracoto durante el periodo del 2010 al 2019.

* Muestra:

  La muestra es la misma de la población, constituida por horas de trabajo acumuladas durante el mes de los últimos 10 años, que fueron registrados por la Municipalidad Distrital de Caracoto durante el periodo 2010 - 2019.

## TÉCNICA E INSTRUMENTO DE RECOLECCIÓN DE DATOS

  * Con el fin de asegurar la efectividad y originalidad de los datos, estos datos fueron recopilados directamente de los registros de horas de trabajo de las maquinarias agrícolas de la Municipalidad Distrital de Caracoto.

## METODOLOGIA DE ANALISIS DE DATOS

  Para el presente trabajo de investigación se analizó los datos mediante los siguientes gráficos:

  + Representación de grafica de la serie de tiempo.
  + Descomposición de datos
  + Diagrama de estacionalidad
  + Diagrama de cajas
  + Histograma
  + Normalidad
  + Test de Pearson
  
  Luego del análisis se trasformo de la serie de datos mediante la aplicación de diferencias de la serie de datos, hasta cumplir con los requisitos necesarios para la aplicación de la metodología de Box – Jenkins.

# RESULTADOS Y DISCUCIÓN
